---
- name: Initiate KubeMasterNode
  become: true
  command: 'kubeadm init --pod-network-cidr=10.244.0.0/16 --token {{ kubetoken }}'

- name: Wait for Initiate
  pause:
    minutes: 4
    prompt: "Waiting..."

- name: FlannelNetwork
  become: true
  command: 'sysctl net.bridge.bridge-nf-call-iptables=1'

- name: FlannelNetworkYaml
  become: true
  command: 'kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml'

- name: RunAsRoot
  become: true
  command: 'export KUBECONFIG=/etc/kubernetes/admin.conf'

- name: copy config file to HOME/.kube dir
  command: "{{ item }}"
  loop:
    - mkdir -p ~{{ansible_remote_user }}/.kube
    - cp /etc/kubernetes/admin.conf ~{{ansible_remote_user }}/.kube/config
    - chown -R {{ ansible_remote_user }}:{{ ansible_remote_user }} ~{{ansible_remote_user }}/.kube
    - chmod 0400 ~{{ansible_remote_user }}/.kube/config
